version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${BACKEND_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_API_URL=${LIVEKIT_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=your_realm
      - KEYCLOAK_CLIENT_ID=your_client_id
      - KEYCLOAK_CLIENT_SECRET=your_client_secret
    depends_on:
      - db
      - keycloak
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - PUBLIC_LIVEKIT_URL=${LIVEKIT_URL}
    depends_on:
      - backend
    restart: unless-stopped

  livekit:
    image: livekit/livekit-server
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    command: --config /livekit-config.yaml
    volumes:
      - ./livekit-config.yaml:/livekit-config.yaml
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: secure_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secure_admin_password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    command:
      - start-dev

volumes:
  postgres_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge
